server:
  port: 10001
spring:
  application:
    name: tensquare-eureka


eureka:
  client:
    fetch-registry: false #是否从eureka中获取注册信息
    register-with-eureka: false #是否将自己注册进eureka,本身就在,无需注册
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
