server:
  port: 9003
spring:
  application:
    name: tensquare-qa #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_qa?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: true
jwt:
  config:
    key: itecast
    ttl: 3600000
eureka:
  instance:
    prefer-ip-address: true #远程调用
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/